"""
Decomposition evaluator for comparing actual vs expected scientific decompositions.

This module provides specialized evaluation for scientific decomposition component,
comparing generated decompositions against expected decompositions from test data.
"""

import sys
from pathlib import Path
from typing import Any, Dict, List

sys.path.append(str(Path(__file__).parent.parent))

from evaluators.base_evaluator import BaseLLMEvaluator
from test_models import EvaluationResult, ExpectedDecomposition


class DecompositionEvaluator(BaseLLMEvaluator):
    """
    Evaluator for scientific decomposition component.

    This evaluator compares the decompositions generated by the scientific
    decomposition component against the expected decompositions defined in test cases.
    """

    def _get_system_prompt(self) -> str:
        """Get system prompt for decomposition evaluation."""
        return """You are an expert evaluator for the scientific decomposition component of a scientific data discovery system.

Your task is to evaluate whether the scientific decompositions generated by the system adequately capture the expected decompositions for a given research topic.

Evaluation Criteria:
1. **Scientific Accuracy**: Do the decompositions represent valid scientific observables/measurements?
2. **Completeness**: Are the essential minimum-required decompositions covered?
3. **Relevance**: Are the decompositions relevant to the research topic and query?
4. **Semantic Similarity**: Are generated decompositions semantically similar to expected ones (even if worded differently)?
5. **Coverage**: Do the decompositions collectively address the research question?

Special considerations:
- **Minimum Requirements**: Expected decompositions marked as "minimum" are critical and must be covered
- **Scientific Terminology**: Different terms may refer to the same scientific concept (e.g., "SST" vs "Sea Surface Temperature")
- **Granularity**: Generated decompositions may be more specific or more general than expected ones
- **Additional Value**: The system may identify valuable decompositions not in the expected list

You must respond in this exact format:
DECISION: PASS or FAIL
CONFIDENCE: A number between 0.0 and 1.0
REASONING: Detailed explanation of your decision, including coverage of minimum requirements and specific comparisons"""

    def _format_user_prompt(
        self,
        actual_output: Any,
        expected_output: Any,
        context: Dict[str, Any],
    ) -> str:
        """Format user prompt for decomposition evaluation."""
        # Extract context
        query = context.get("query", "Unknown query")
        topic_title = context.get("topic_title", "Unknown topic")

        # Format expected decompositions
        expected_decompositions = (
            expected_output if isinstance(expected_output, list) else []
        )
        expected_str = ""
        minimum_count = 0

        for decomp in expected_decompositions:
            minimum_flag = " [MINIMUM REQUIRED]" if decomp.is_minimum else ""
            if decomp.is_minimum:
                minimum_count += 1

            expected_str += f"- {decomp.title}{minimum_flag}\n"
            if decomp.justification:
                expected_str += f"  Justification: {decomp.justification[:150]}...\n"

        # Format actual decompositions
        actual_decompositions = []
        if hasattr(actual_output, "decompositions"):
            actual_decompositions = actual_output.decompositions
        elif isinstance(actual_output, list):
            actual_decompositions = actual_output

        actual_str = ""
        for decomp in actual_decompositions:
            actual_str += f"- {self._format_decomposition(decomp)}\n"

        return f"""Research Query: "{query}"
Topic: "{topic_title}"

Expected Decompositions ({len(expected_decompositions)} total, {minimum_count} minimum required):
{expected_str}

Generated Decompositions ({len(actual_decompositions)} total):
{actual_str}

Please evaluate whether the generated decompositions adequately cover the expected decompositions, paying special attention to minimum required decompositions."""

    def _format_decomposition(self, decomp: Any) -> str:
        """Format a single decomposition for display."""
        if hasattr(decomp, "title"):
            title = decomp.title
            justification = getattr(decomp, "scientific_justification", "")
            if justification and len(justification) > 100:
                justification = justification[:100] + "..."
            return f"{title}" + (
                f" (Justification: {justification})" if justification else ""
            )
        else:
            return str(decomp)

    def _get_component_name(self) -> str:
        """Get component name."""
        return "scientific_decomposition"

    async def evaluate_detailed(
        self,
        actual_decompositions: List[Any],
        expected_decompositions: List[ExpectedDecomposition],
        query: str,
        topic_title: str = "",
    ) -> EvaluationResult:
        """
        Perform detailed decomposition evaluation with minimum requirement checking.

        Args:
            actual_decompositions: Decompositions generated by the system
            expected_decompositions: Expected decompositions from test case
            query: Original research query
            topic_title: Title of the topic being decomposed

        Returns:
            EvaluationResult with detailed decomposition analysis
        """
        context = {
            "query": query,
            "topic_title": topic_title,
            "expected_count": len(expected_decompositions),
            "actual_count": len(actual_decompositions),
            "minimum_count": len([d for d in expected_decompositions if d.is_minimum]),
        }

        # Perform basic evaluation
        result = await self.evaluate(
            actual_decompositions,
            expected_decompositions,
            context,
        )

        # Add specific feedback for decompositions
        minimum_coverage = self._check_minimum_coverage(
            actual_decompositions,
            expected_decompositions,
        )
        coverage_analysis = self._analyze_decomposition_coverage(
            actual_decompositions,
            expected_decompositions,
        )

        specific_feedback = {
            "expected_decompositions_count": len(expected_decompositions),
            "actual_decompositions_count": len(actual_decompositions),
            "minimum_required_count": context["minimum_count"],
            "minimum_coverage": minimum_coverage,
            "coverage_analysis": coverage_analysis,
            "missing_minimum_decompositions": self._find_missing_minimum(
                actual_decompositions,
                expected_decompositions,
            ),
            "covered_minimum_decompositions": self._find_covered_minimum(
                actual_decompositions,
                expected_decompositions,
            ),
            "additional_decompositions": self._find_additional_decompositions(
                actual_decompositions,
                expected_decompositions,
            ),
        }

        result.specific_feedback.update(specific_feedback)

        # Override pass/fail based on minimum coverage
        if (
            not minimum_coverage["all_covered"]
            and minimum_coverage["missing_count"] > 0
        ):
            result.passed = False
            result.reasoning += f"\n\nFAILED: Missing {minimum_coverage['missing_count']} minimum required decompositions: {minimum_coverage['missing']}"

        return result

    def _check_minimum_coverage(
        self,
        actual_decompositions: List[Any],
        expected_decompositions: List[ExpectedDecomposition],
    ) -> Dict[str, Any]:
        """Check coverage of minimum required decompositions."""
        minimum_decomps = [d for d in expected_decompositions if d.is_minimum]
        actual_titles = [
            self._get_decomposition_title(d).lower() for d in actual_decompositions
        ]

        covered = []
        missing = []

        for min_decomp in minimum_decomps:
            found_match = False
            min_words = set(min_decomp.title.lower().split())

            for actual_title in actual_titles:
                actual_words = set(actual_title.split())
                overlap = len(min_words & actual_words)
                overlap_ratio = overlap / len(min_words) if min_words else 0

                # Consider it covered if there's significant word overlap
                if overlap_ratio >= 0.5 or self._check_semantic_similarity(
                    min_decomp.title,
                    actual_title,
                ):
                    found_match = True
                    covered.append(min_decomp.title)
                    break

            if not found_match:
                missing.append(min_decomp.title)

        return {
            "total_minimum": len(minimum_decomps),
            "covered_count": len(covered),
            "missing_count": len(missing),
            "covered": covered,
            "missing": missing,
            "all_covered": len(missing) == 0,
        }

    def _analyze_decomposition_coverage(
        self,
        actual_decompositions: List[Any],
        expected_decompositions: List[ExpectedDecomposition],
    ) -> Dict[str, Any]:
        """Analyze overall decomposition coverage."""
        coverage = {
            "well_covered": [],
            "partially_covered": [],
            "not_covered": [],
        }

        actual_titles = [
            self._get_decomposition_title(d) for d in actual_decompositions
        ]

        for expected in expected_decompositions:
            best_match = None
            best_score = 0

            expected_words = set(expected.title.lower().split())

            for actual_title in actual_titles:
                actual_words = set(actual_title.lower().split())
                overlap = len(expected_words & actual_words)
                score = overlap / len(expected_words) if expected_words else 0

                if score > best_score:
                    best_score = score
                    best_match = actual_title

            if best_score >= 0.7:
                coverage["well_covered"].append(
                    {
                        "expected": expected.title,
                        "matched_with": best_match,
                        "score": best_score,
                        "is_minimum": expected.is_minimum,
                    },
                )
            elif best_score >= 0.3:
                coverage["partially_covered"].append(
                    {
                        "expected": expected.title,
                        "best_match": best_match,
                        "score": best_score,
                        "is_minimum": expected.is_minimum,
                    },
                )
            else:
                coverage["not_covered"].append(
                    {
                        "expected": expected.title,
                        "is_minimum": expected.is_minimum,
                    },
                )

        return coverage

    def _find_missing_minimum(
        self,
        actual_decompositions: List[Any],
        expected_decompositions: List[ExpectedDecomposition],
    ) -> List[str]:
        """Find minimum required decompositions that are missing."""
        minimum_coverage = self._check_minimum_coverage(
            actual_decompositions,
            expected_decompositions,
        )
        return minimum_coverage["missing"]

    def _find_covered_minimum(
        self,
        actual_decompositions: List[Any],
        expected_decompositions: List[ExpectedDecomposition],
    ) -> List[str]:
        """Find minimum required decompositions that are covered."""
        minimum_coverage = self._check_minimum_coverage(
            actual_decompositions,
            expected_decompositions,
        )
        return minimum_coverage["covered"]

    def _find_additional_decompositions(
        self,
        actual_decompositions: List[Any],
        expected_decompositions: List[ExpectedDecomposition],
    ) -> List[str]:
        """Find decompositions that weren't in the expected list."""
        expected_titles = [e.title.lower() for e in expected_decompositions]
        additional = []

        for actual in actual_decompositions:
            actual_title = self._get_decomposition_title(actual)
            actual_words = set(actual_title.lower().split())

            found_match = False
            for expected_title in expected_titles:
                expected_words = set(expected_title.split())
                overlap = len(actual_words & expected_words)
                if overlap >= len(actual_words) * 0.5:  # 50% word overlap
                    found_match = True
                    break

            if not found_match:
                additional.append(actual_title)

        return additional

    def _check_semantic_similarity(self, text1: str, text2: str) -> bool:
        """
        Check semantic similarity between two decomposition titles.

        This is a simple implementation - could be enhanced with proper
        semantic similarity models or domain-specific term matching.
        """
        # Simple checks for common scientific term variations
        synonyms = {
            "sst": "sea surface temperature",
            "temperature": "thermal",
            "precipitation": "rainfall",
            "vegetation": "plants",
            "biomass": "vegetation",
            "moisture": "water",
            "albedo": "reflectance",
        }

        text1_lower = text1.lower()
        text2_lower = text2.lower()

        # Check for exact substring matches
        if text1_lower in text2_lower or text2_lower in text1_lower:
            return True

        # Check for synonym matches
        for synonym, canonical in synonyms.items():
            if (synonym in text1_lower and canonical in text2_lower) or (
                canonical in text1_lower and synonym in text2_lower
            ):
                return True

        return False

    def _get_decomposition_title(self, decomp: Any) -> str:
        """Extract title from a decomposition object."""
        if hasattr(decomp, "title"):
            return decomp.title
        elif isinstance(decomp, dict) and "title" in decomp:
            return decomp["title"]
        else:
            return str(decomp)
