"""
Topic evaluator for comparing actual vs expected topics.

This module provides specialized evaluation for topic splitting component,
comparing generated topics against expected topics from test data.
"""

import sys
from pathlib import Path
from typing import Any, Dict, List

sys.path.append(str(Path(__file__).parent.parent))

from evaluators.base_evaluator import BaseLLMEvaluator
from test_models import EvaluationResult, ExpectedTopic


class TopicEvaluator(BaseLLMEvaluator):
    """
    Evaluator for topic splitting component.

    This evaluator compares the topics generated by the topic splitting
    component against the expected topics defined in test cases.
    """

    def _get_system_prompt(self) -> str:
        """Get system prompt for topic evaluation."""
        return """You are an expert evaluator for the topic splitting component of a scientific data discovery system.

Your task is to evaluate whether the topics generated by the system adequately capture the expected topics for a given research query.

Evaluation Criteria:
1. **Coverage**: Do the generated topics cover the main subject areas identified in the expected topics?
2. **Semantic Similarity**: Are the generated topics semantically similar to expected topics (even if worded differently)?
3. **Completeness**: Are all important aspects from expected topics represented?
4. **Relevance**: Are the generated topics relevant to the original research query?

Consider that:
- Exact wording is not required - semantic similarity is more important
- Generated topics may be more specific or more general than expected topics
- The system may identify additional relevant topics not in the expected list
- Focus on whether the generated topics would lead to finding the right type of data

You must respond in this exact format:
DECISION: PASS or FAIL
CONFIDENCE: A number between 0.0 and 1.0
REASONING: Detailed explanation of your decision, including specific comparisons between expected and actual topics"""

    def _format_user_prompt(
        self,
        actual_output: Any,
        expected_output: Any,
        context: Dict[str, Any],
    ) -> str:
        """Format user prompt for topic evaluation."""
        # Extract query from context
        query = context.get("query", "Unknown query")

        # Format expected topics
        expected_topics = expected_output if isinstance(expected_output, list) else []
        expected_str = "\n".join(
            [
                f"- {topic.title} (category: {topic.category.value})"
                for topic in expected_topics
            ],
        )

        # Format actual topics
        actual_topics = []
        if hasattr(actual_output, "topics"):
            actual_topics = actual_output.topics
        elif isinstance(actual_output, list):
            actual_topics = actual_output

        actual_str = "\n".join(
            [f"- {self._format_topic(topic)}" for topic in actual_topics],
        )

        return f"""Research Query: "{query}"

Expected Topics:
{expected_str}

Generated Topics:
{actual_str}

Please evaluate whether the generated topics adequately capture the expected topics for this research query."""

    def _format_topic(self, topic: Any) -> str:
        """Format a single topic for display."""
        if hasattr(topic, "title"):
            title = topic.title
            context = getattr(topic, "functional_context", "")
            if context and len(context) > 100:
                context = context[:100] + "..."
            return f"{title}" + (f" ({context})" if context else "")
        else:
            return str(topic)

    def _get_component_name(self) -> str:
        """Get component name."""
        return "topic_splitting"

    async def evaluate_detailed(
        self,
        actual_topics: List[Any],
        expected_topics: List[ExpectedTopic],
        query: str,
    ) -> EvaluationResult:
        """
        Perform detailed topic evaluation with additional analysis.

        Args:
            actual_topics: Topics generated by the system
            expected_topics: Expected topics from test case
            query: Original research query

        Returns:
            EvaluationResult with detailed topic analysis
        """
        context = {
            "query": query,
            "expected_count": len(expected_topics),
            "actual_count": len(actual_topics),
        }

        # Perform basic evaluation
        result = await self.evaluate(actual_topics, expected_topics, context)

        # Add specific feedback for topics
        specific_feedback = {
            "expected_topics_count": len(expected_topics),
            "actual_topics_count": len(actual_topics),
            "topic_coverage_analysis": self._analyze_topic_coverage(
                actual_topics,
                expected_topics,
            ),
            "missing_topics": self._find_missing_topics(actual_topics, expected_topics),
            "additional_topics": self._find_additional_topics(
                actual_topics,
                expected_topics,
            ),
        }

        result.specific_feedback.update(specific_feedback)
        return result

    def _analyze_topic_coverage(
        self,
        actual_topics: List[Any],
        expected_topics: List[ExpectedTopic],
    ) -> Dict[str, Any]:
        """Analyze how well actual topics cover expected topics."""
        coverage = {
            "covered_topics": [],
            "partially_covered": [],
            "missing_topics": [],
        }

        actual_titles = [self._get_topic_title(t) for t in actual_topics]

        for expected in expected_topics:
            # Simple keyword matching for coverage analysis
            expected_words = set(expected.title.lower().split())

            best_match = None
            best_score = 0

            for actual_title in actual_titles:
                actual_words = set(actual_title.lower().split())
                overlap = len(expected_words & actual_words)
                score = overlap / len(expected_words) if expected_words else 0

                if score > best_score:
                    best_score = score
                    best_match = actual_title

            if best_score >= 0.7:
                coverage["covered_topics"].append(
                    {
                        "expected": expected.title,
                        "matched_with": best_match,
                        "score": best_score,
                    },
                )
            elif best_score >= 0.3:
                coverage["partially_covered"].append(
                    {
                        "expected": expected.title,
                        "best_match": best_match,
                        "score": best_score,
                    },
                )
            else:
                coverage["missing_topics"].append(expected.title)

        return coverage

    def _find_missing_topics(
        self,
        actual_topics: List[Any],
        expected_topics: List[ExpectedTopic],
    ) -> List[str]:
        """Find expected topics that seem to be missing from actual topics."""
        # This is a simplified implementation - would benefit from better semantic matching
        actual_titles = [self._get_topic_title(t).lower() for t in actual_topics]
        missing = []

        for expected in expected_topics:
            expected_words = set(expected.title.lower().split())
            found_match = False

            for actual_title in actual_titles:
                actual_words = set(actual_title.split())
                overlap = len(expected_words & actual_words)
                if overlap >= len(expected_words) * 0.5:  # 50% word overlap
                    found_match = True
                    break

            if not found_match:
                missing.append(expected.title)

        return missing

    def _find_additional_topics(
        self,
        actual_topics: List[Any],
        expected_topics: List[ExpectedTopic],
    ) -> List[str]:
        """Find actual topics that weren't in the expected list."""
        expected_titles = [e.title.lower() for e in expected_topics]
        additional = []

        for actual in actual_topics:
            actual_title = self._get_topic_title(actual)
            actual_words = set(actual_title.lower().split())

            found_match = False
            for expected_title in expected_titles:
                expected_words = set(expected_title.split())
                overlap = len(actual_words & expected_words)
                if overlap >= len(actual_words) * 0.5:  # 50% word overlap
                    found_match = True
                    break

            if not found_match:
                additional.append(actual_title)

        return additional

    def _get_topic_title(self, topic: Any) -> str:
        """Extract title from a topic object."""
        if hasattr(topic, "title"):
            return topic.title
        elif isinstance(topic, dict) and "title" in topic:
            return topic["title"]
        else:
            return str(topic)
