model_name = "gpt-4o-mini"
api_key = ""
temperature = 0
system_prompt = ""

[docling_scraper_config]
debug = false
do_table_structure = true
pdf_mode = "accurate"
export_type = "html"

[s2_tool_config]
api_key = ""
debug = false
external_id = "ARXIV"
fields = [
  "paperId",
  "externalIds",
  "url",
  "title",
  "abstract",
  "year",
  "authors.name",
  "isOpenAccess",
  "openAccessPdf"
]