[search]
base_url = "http://localhost:8080"
max_results = 5
engines = ["google", "arxiv", "google_scholar"]
max_pages = 25
results_per_page = 10
score_cutoff = 0.25
debug = true

[scraper]
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
timeout = 20
max_content_length = 1000000
debug = true