[search]
base_url = "http://localhost:8080"
max_results = 5
engines = ["google", "arxiv", "google_scholar"]
max_pages = 25
results_per_page = 10
score_cutoff = 0.25
debug = true

[scraper]
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
timeout = 20
max_content_length = 1000000
debug = true

[vectordb_search]
embedding_model = "sentence-transformers/all-MiniLM-L6-v2"
milvus_uri = "tmp/milvus/litagent.db"
collection_name = "litagent_demo"
drop_old = true
k = 25

[fact_reasoner]
gen_model = "mixtral-8x7b-instruct"
k = 5
context_retriever_service_type = "google"
merlin_path = "/Users/npantha/bin/merlin"
db_path = "tmp/milvus/litagent.db"
collection_name = "litagent_demo"
cache_dir = "tmp/cache.db"
