"""
LLM-based interactive workflow planner for AKD.

This module provides an intelligent planner that can converse with users to understand
their research requirements and generate validated workflow definitions in the AKD format.
"""

from typing import Any, Dict, List, Optional, Union
from enum import Enum

from loguru import logger
from pydantic import Field

from akd._base import InputSchema, OutputSchema
from akd.agents._base import InstructorBaseAgent, BaseAgentConfig

from .registry import AgentRegistry, get_agent_registry
from .format_builder import WorkflowFormat
from .workflow_builder import WorkflowBuilder
from .field_mapping_registry import FieldMappingRegistry
from .field_mapping_generator import FieldMappingGenerator
from .structures import AgentSuggestion, WorkflowPlan


class ConversationPhase(str, Enum):
    """Phases of the planning conversation."""

    INITIAL_REQUIREMENTS = "initial_requirements"
    GOAL_CLARIFICATION = "goal_clarification"
    AGENT_SELECTION = "agent_selection"
    IO_SPECIFICATION = "io_specification"
    WORKFLOW_CONSTRUCTION = "workflow_construction"
    VALIDATION = "validation"
    FINALIZATION = "finalization"


class PlannerQuestionType(str, Enum):
    """Types of questions the planner can ask."""

    OPEN_ENDED = "open_ended"
    MULTIPLE_CHOICE = "multiple_choice"
    CONFIRMATION = "confirmation"
    SPECIFICATION = "specification"


class PlannerQuestion(OutputSchema):
    """Question generated by the planner."""

    question: str = Field(..., description="The question to ask the user")
    question_type: PlannerQuestionType = Field(..., description="Type of question")
    options: Optional[List[str]] = Field(
        default=None, description="Options for multiple choice questions"
    )
    context: str = Field(
        ..., description="Context explaining why this question is important"
    )
    suggested_answer: Optional[str] = Field(
        default=None, description="Suggested answer if applicable"
    )


# AgentSuggestion and WorkflowPlan are now imported from structures.py


class PlannerResponse(OutputSchema):
    """Response from the planner agent."""

    message: str = Field(..., description="Response message to the user")
    phase: ConversationPhase = Field(..., description="Current conversation phase")
    question: Optional[PlannerQuestion] = Field(
        default=None, description="Follow-up question if needed"
    )
    workflow_plan: Optional[WorkflowPlan] = Field(
        default=None, description="Generated workflow plan"
    )
    ready_to_generate: bool = Field(
        default=False, description="Whether ready to generate final workflow"
    )


class PlannerInput(InputSchema):
    """Input to the planner agent."""

    user_message: str = Field(..., description="User's message or response")
    conversation_history: List[Dict[str, str]] = Field(
        default_factory=list, description="Previous conversation"
    )
    current_phase: ConversationPhase = Field(
        default=ConversationPhase.INITIAL_REQUIREMENTS
    )
    available_agents: List[Dict[str, Any]] = Field(
        default_factory=list, description="Available agents from registry"
    )


class LLMWorkflowPlanner(InstructorBaseAgent[PlannerInput, PlannerResponse]):
    """LLM-based workflow planner with conversational interface."""

    input_schema = PlannerInput
    output_schema = PlannerResponse

    def __init__(
        self,
        config: Optional[BaseAgentConfig] = None,
        registry: Optional[AgentRegistry] = None,
        mapping_registry: Optional[FieldMappingRegistry] = None,
        mapping_generator: Optional[FieldMappingGenerator] = None,
        debug: bool = False,
    ):
        """Initialize the planner."""
        self.registry = registry or get_agent_registry()
        self.mapping_registry = mapping_registry or FieldMappingRegistry()
        self.mapping_generator = mapping_generator or FieldMappingGenerator()
        self.builder = WorkflowBuilder(self.registry, self.mapping_registry)
        self.conversation_state: Dict[str, Any] = {}

        # Set up system prompt for workflow planning (uses self.registry)
        planner_config = config or BaseAgentConfig()
        planner_config.system_prompt = self._get_planner_system_prompt()
        # Lower temperature for more deterministic, decisive workflow generation
        if not planner_config.temperature:
            planner_config.temperature = 0.3

        super().__init__(config=planner_config, debug=debug)

    def _get_planner_system_prompt(self) -> str:
        """Get the system prompt for the planner."""
        # Build available agents section dynamically from registry
        agents_info = []
        for agent in self.registry.get_enabled_agents():
            agent_desc = f"- **{agent.agent_id}**: {agent.description}"

            # Add input/output info
            inputs = [f.name for f in agent.input_schema.fields if f.required]
            outputs = [f.name for f in agent.output_schema.fields]

            if inputs:
                agent_desc += f"\n  - Required inputs: {', '.join(inputs)}"
            if outputs:
                agent_desc += f"\n  - Outputs: {', '.join(outputs)}"

            agents_info.append(agent_desc)

        available_agents_text = "\n".join(agents_info) if agents_info else "No agents available"

        return f"""You are an intelligent workflow planner for the AKD (Accelerated Knowledge Discovery) research framework.

Your goal is to design scientifically sound, executable workflows with correct data flow between agents.

**WORKFLOW GENERATION STRATEGY:**

1. **Analyze the Request**: Understand what the user wants to accomplish
2. **Generate Workflow Immediately**: For clear requests with obvious agent sequences, provide workflow_plan in first response
3. **Use Reasonable Defaults**: Time ranges (recent/last 5 years), databases (standard academic), formats (structured output)
4. **Ask Questions ONLY if**: Request is genuinely ambiguous OR multiple valid workflows with significantly different outcomes exist

**IMPERATIVE: If user request mentions specific workflow steps (e.g., "search papers and extract findings"), generate the workflow_plan immediately. DO NOT ask clarifying questions about minor details.**

**CRITICAL: Data Flow Requirements**
When suggesting agents, MUST verify:
- Each agent's **required** input fields can be satisfied by previous agents' outputs
- Field types are compatible (e.g., array of strings can flow to list field)
- Field semantics match (e.g., "queries" → "query", "results" → "content")
- Data transformations are logical (query → search → extraction)

**Agent Selection Process:**
1. Review available agents' input_schema and output_schema
2. Match agent capabilities to user's research goal
3. Chain agents so outputs satisfy next agent's required inputs
4. Verify data flow: agent A outputs must include agent B's required inputs

**When to Ask Questions:**
✓ ASK if user goal is genuinely ambiguous (e.g., "analyze data" - what kind?)
✓ ASK if multiple valid workflows exist and choice impacts results significantly
✗ DON'T ASK about minor details (time ranges, database preferences, output formats)
✗ DON'T ASK about standard assumptions (recent papers, peer-reviewed sources)

**When to Generate Workflow:**
- Request clearly specifies: search → process → extract pattern
- Agent sequence is obvious from research goal
- Data flow between agents is valid
- After 1-2 clarifying exchanges if needed

**CRITICAL: Field Input Handling Strategy**

For FIRST agent in workflow:
- **Required fields**: Extract from user query; ASK user if genuinely missing from request
- **Optional fields**: Provide sensible defaults/hints based on context
  - Examples: max_results=20-30, category inferred from topic keywords, time_range="recent"
  - Make context-aware suggestions (e.g., "protein" → category="computational-biology")

For SUBSEQUENT agents in workflow:
- **Auto-mappable fields**: If field can be satisfied by previous agent's output via io_map → DO NOT fill it manually
  - Let io_map handle runtime data routing (e.g., search_results ← previous_agent.results)
  - Check field mappings: explicit mappings, exact name matches, or semantic mappings
- **User-specified fields**: Only fill fields that CANNOT be auto-mapped from previous agent
  - Required fields with no mapping → ASK user (if critical) or use reasonable inference
  - Optional fields → Provide context-aware defaults
- **Example**:
  - gap_analysis.search_results ← deep_search.results (AUTO-MAPPED via io_map, don't fill)
  - gap_analysis.gap ← user must specify type (e.g., "methodology", "dataset") - extract from query or ask

**Key Principle**: Minimize user burden by auto-mapping when possible, only ask for genuinely missing critical information.

**Workflow Plan Requirements:**
When providing workflow_plan, include:
- workflow_description: Clear summary of what it does
- research_goal: What user wants to accomplish
- suggested_agents: Agents with **EXACT agent_id from available_agents list**, required_inputs, expected_outputs, depends_on
- workflow_steps: High-level steps showing data flow
- Set ready_to_generate=True

**CRITICAL: Use EXACT agent IDs from the available_agents list below. Do NOT invent agent names or add suffixes like "_agent".**

**Available Agents:**
{available_agents_text}

**Response Guidelines:**
- Be concise and actionable
- Explain data flow logic clearly
- Only ask questions that materially impact workflow correctness
- Generate workflows decisively when request is clear
- Focus on technical soundness and correct IO matching
- ONLY use agent IDs from the list above"""

    def reset_conversation(self) -> None:
        """Reset the conversation state."""
        self.conversation_state = {}
        self.reset_memory()

    async def plan_workflow(self, initial_request: str) -> "InteractivePlannerSession":
        """Start an interactive planning session."""
        return InteractivePlannerSession(self, initial_request)

    async def _arun(self, params: PlannerInput, **kwargs) -> PlannerResponse:
        """Process user input and generate planner response."""
        try:
            # Get available agents information with detailed schemas
            available_agents = []
            for agent in self.registry.get_enabled_agents():
                agent_info = {
                    "id": agent.agent_id,
                    "name": agent.name,
                    "description": agent.description,
                    "input_schema": [
                        {
                            "name": f.name,
                            "type": f.type,
                            "description": f.description,
                            "required": f.required,
                        }
                        for f in agent.input_schema.fields
                    ],
                    "output_schema": [
                        {
                            "name": f.name,
                            "type": f.type,
                            "description": f.description,
                        }
                        for f in agent.output_schema.fields
                    ],
                    "use_cases": agent.use_cases,
                    "tags": agent.tags,
                }
                available_agents.append(agent_info)

            # Update input with available agents
            params.available_agents = available_agents

            # Build messages for LLM
            messages = [self._default_system_message()]

            # Add conversation history
            for msg in params.conversation_history:
                messages.append(msg)

            # Add current user message
            messages.append(
                {
                    "role": "user",
                    "content": f"Current phase: {params.current_phase}\nUser message: {params.user_message}",
                }
            )

            # Get response from LLM
            response = await self.get_response_async(messages)

            if self.debug:
                logger.debug(f"Planner response: {response}")

            return response

        except Exception as e:
            logger.error(f"Error in planner execution: {e}")
            return PlannerResponse(
                message=f"I encountered an error while processing your request: {e}",
                phase=params.current_phase,
                ready_to_generate=False,
            )


class InteractivePlannerSession:
    """Interactive session for workflow planning."""

    def __init__(self, planner: LLMWorkflowPlanner, initial_request: str):
        """Initialize planning session."""
        self.planner = planner
        self.initial_request = initial_request
        self.conversation_history: List[Dict[str, str]] = []
        self.current_phase = ConversationPhase.INITIAL_REQUIREMENTS
        self.workflow_plan: Optional[WorkflowPlan] = None
        self.final_workflow: Optional[WorkflowFormat] = None

    async def start(self) -> PlannerResponse:
        """Start the planning conversation."""
        response = await self.planner._arun(
            PlannerInput(
                user_message=self.initial_request,
                conversation_history=self.conversation_history,
                current_phase=self.current_phase,
            )
        )

        self._update_session_state(self.initial_request, response)
        return response

    async def respond(self, user_message: str) -> PlannerResponse:
        """Process user response and continue conversation."""
        response = await self.planner._arun(
            PlannerInput(
                user_message=user_message,
                conversation_history=self.conversation_history,
                current_phase=self.current_phase,
            )
        )

        self._update_session_state(user_message, response)
        return response

    def _update_session_state(
        self, user_message: str, response: PlannerResponse
    ) -> None:
        """Update session state with new messages."""
        self.conversation_history.append({"role": "user", "content": user_message})
        self.conversation_history.append(
            {"role": "assistant", "content": response.message}
        )

        self.current_phase = response.phase

        if response.workflow_plan:
            self.workflow_plan = response.workflow_plan

    async def generate_workflow(self) -> WorkflowFormat:
        """Generate the final workflow from the conversation."""
        if not self.workflow_plan:
            raise ValueError(
                "No workflow plan available. Continue the conversation first."
            )

        # Simple validation: check agents exist
        missing_agents = self.planner.builder.check_missing_agents(self.workflow_plan)
        if missing_agents:
            raise ValueError(f"Agents not found in registry: {missing_agents}")

        # Fill inputs for each agent
        filled_inputs = await self._fill_all_agent_inputs(self.workflow_plan)

        # Check for unmapped fields that need LLM generation
        unmapped = self.planner.builder.identify_unmapped_fields(
            self.workflow_plan,
            filled_inputs
        )

        # Generate and approve field mappings if needed
        if unmapped:
            logger.info(f"Found {len(unmapped)} unmapped field sets requiring LLM mapping")
            await self._handle_unmapped_fields(unmapped)

        # Build workflow with io_map for runtime data flow
        workflow = self.planner.builder.build(self.workflow_plan, filled_inputs)

        if self.planner.debug:
            logger.debug(f"Generated workflow with {len(workflow.nodes)} nodes")

        self.final_workflow = workflow
        return workflow

    async def _handle_unmapped_fields(
        self,
        unmapped: List[Dict[str, Any]],
        confidence_threshold: float = 0.8
    ) -> None:
        """
        Generate LLM mappings for unmapped fields and handle user approval.

        Args:
            unmapped: List of unmapped field info from identify_unmapped_fields()
            confidence_threshold: Threshold for auto-approval
        """
        for item in unmapped:
            source_agent_id = item["source_agent_id"]
            target_agent_id = item["target_agent_id"]
            unmapped_fields = item["unmapped_fields"]

            source_agent = self.planner.registry.get_agent(source_agent_id)
            target_agent = self.planner.registry.get_agent(target_agent_id)

            if not source_agent or not target_agent:
                logger.error(
                    f"Cannot generate mapping: agent not found "
                    f"({source_agent_id} or {target_agent_id})"
                )
                continue

            logger.info(
                f"Generating LLM mapping for {source_agent_id} -> {target_agent_id}"
            )

            # Generate mapping using LLM
            try:
                result = await self.planner.mapping_generator.generate_mapping(
                    source_agent,
                    target_agent,
                    unmapped_fields
                )

                # Check if approval needed
                needs_approval = self.planner.mapping_generator.should_request_approval(
                    result,
                    confidence_threshold
                )

                if needs_approval:
                    # Format approval message
                    approval_msg = self.planner.mapping_generator.format_approval_message(
                        source_agent,
                        target_agent,
                        result
                    )

                    # Log approval request (in interactive mode, this would prompt user)
                    logger.info(f"\n{approval_msg}")
                    logger.warning(
                        "Low confidence mapping detected. Approval required. "
                        "Auto-approving for now (interactive mode not implemented)."
                    )

                    # TODO: In full interactive mode, wait for user approval here
                    # For now, auto-approve with warning
                    user_approved = True
                else:
                    user_approved = True
                    logger.info(
                        f"Auto-approved mapping with confidence {result.overall_confidence:.2f}"
                    )

                # Save mapping to registry
                mapping_dict = self.planner.mapping_generator.convert_to_mapping_dict(result)
                reasoning_dict = self.planner.mapping_generator.extract_reasoning(result)

                self.planner.mapping_registry.save_llm_mapping(
                    source_agent_id,
                    target_agent_id,
                    mapping_dict,
                    result.overall_confidence,
                    user_approved,
                    reasoning_dict
                )

                logger.info(
                    f"Saved LLM mapping: {source_agent_id} -> {target_agent_id} "
                    f"(approved={user_approved})"
                )

            except Exception as e:
                logger.error(
                    f"Failed to generate LLM mapping for "
                    f"{source_agent_id} -> {target_agent_id}: {e}"
                )

    async def _fill_all_agent_inputs(self, plan: WorkflowPlan) -> Dict[str, Dict[str, Any]]:
        """Fill inputs for all agents in the plan."""
        filled_inputs = {}

        for agent_suggestion in plan.suggested_agents:
            agent_id = agent_suggestion.agent_id
            agent = self.planner.registry.get_agent(agent_id)

            if not agent:
                logger.warning(f"Agent {agent_id} not in registry, skipping")
                continue

            try:
                inputs = await self._fill_inputs_with_llm(agent, agent_id)
                filled_inputs[agent_id] = inputs
            except Exception as e:
                logger.warning(f"Failed to fill inputs for {agent_id}: {e}")
                # Fallback to rule-based
                inputs = self._fallback_input_extraction(agent, agent_id)
                filled_inputs[agent_id] = inputs

        return filled_inputs

    async def _fill_inputs_with_llm(self, agent: Any, agent_id: str) -> Dict[str, Any]:
        """Use Instructor LLM to extract structured input values from user context."""
        from pydantic import create_model, Field as PydanticField
        from typing import get_type_hints
        import instructor

        # Build a dynamic Pydantic model from the agent's input schema
        field_definitions = {}
        field_descriptions = {}

        for field in agent.input_schema.fields:
            # Determine Python type from string type
            python_type = Any
            if "string" in field.type.lower() or "str" in field.type.lower():
                python_type = str
            elif "int" in field.type.lower():
                python_type = int
            elif "float" in field.type.lower() or "number" in field.type.lower():
                python_type = float
            elif "bool" in field.type.lower():
                python_type = bool
            elif "list" in field.type.lower() or "array" in field.type.lower():
                python_type = list[str]  # Default to list of strings

            # Make optional if not required
            if not field.required:
                python_type = Optional[python_type]

            # Store description
            description = field.description or f"{field.name} for {agent_id}"
            field_descriptions[field.name] = description

            # Create field with default if not required
            if field.required:
                field_definitions[field.name] = (
                    python_type,
                    PydanticField(description=description)
                )
            else:
                field_definitions[field.name] = (
                    python_type,
                    PydanticField(default=None, description=description)
                )

        # Create dynamic model
        InputModel = create_model(
            f"{agent_id.title()}Input",
            **field_definitions
        )

        # Use Instructor to extract structured data
        try:
            client = self.planner.client

            prompt = f"""Extract the input parameters for the '{agent_id}' agent from this user request.

User Request: {self.initial_request}

Agent: {agent_id}
Agent Description: {agent.description if hasattr(agent, 'description') else 'N/A'}

Input Fields Needed:
{chr(10).join(f"- {name}: {desc}" for name, desc in field_descriptions.items())}

Instructions:
- Extract values directly from the user request where mentioned
- For 'query' fields: use the user's research question
- For 'category' fields: infer from topic keywords
- For 'max_results' or 'limit': use reasonable defaults (20-50)
- For other fields: use context-appropriate values or reasonable defaults
- Be specific and relevant to the user's actual request
"""

            response = await client.chat.completions.create(
                model=self.planner.config.model_name,
                response_model=InputModel,
                messages=[
                    {"role": "system", "content": "You are an expert at extracting structured parameters from research requests."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.1,
            )

            # Convert to dict
            return response.model_dump()

        except Exception as e:
            logger.warning(f"LLM-based input filling failed for {agent_id}: {e}")
            # Fall back to simpler extraction
            return self._fallback_input_extraction(agent, agent_id)

    def _fallback_input_extraction(self, agent: Any, agent_id: str) -> Dict[str, Any]:
        """Fallback simple rule-based extraction when LLM fails."""
        user_query = self.initial_request
        result = {}

        for field in agent.input_schema.fields:
            value = None

            # Rule-based extraction
            if field.name == "query":
                value = user_query
            elif field.name == "queries":
                value = [user_query]
            elif field.name == "category":
                query_lower = user_query.lower()
                if any(term in query_lower for term in ["protein", "alphafold", "structure"]):
                    value = "computational-biology"
                elif any(term in query_lower for term in ["machine learning", "deep learning", "neural"]):
                    value = "machine-learning"
                elif any(term in query_lower for term in ["drug", "medicine", "therapeutic"]):
                    value = "drug-discovery"
                else:
                    value = "research"
            elif field.name in ["max_results", "limit"]:
                value = 20
            elif field.name == "gap":
                if "gap" in user_query.lower():
                    value = "research gaps"
                else:
                    value = "methodological gaps"

            # Use default if nothing extracted
            if value is None:
                value = self._get_default_value(field.type, field.name, field)

            result[field.name] = value

        return result


    def get_conversation_summary(self) -> str:
        """Get a summary of the conversation."""
        summary = "Planning Session Summary:\n"
        summary += f"Initial Request: {self.initial_request}\n"
        summary += f"Current Phase: {self.current_phase}\n"

        if self.workflow_plan:
            summary += f"Research Goal: {self.workflow_plan.research_goal}\n"
            summary += f"Suggested Agents: {[a.agent_name for a in self.workflow_plan.suggested_agents]}\n"

        return summary


# Convenience functions
async def create_planner(
    config: Optional[BaseAgentConfig] = None, registry: Optional[AgentRegistry] = None
) -> LLMWorkflowPlanner:
    """Create a new workflow planner instance."""
    return LLMWorkflowPlanner(config=config, registry=registry)


async def quick_plan(
    research_goal: str, config: Optional[BaseAgentConfig] = None
) -> InteractivePlannerSession:
    """Create a quick planning session for a research goal."""
    planner = await create_planner(config=config)
    return await planner.plan_workflow(research_goal)
