"""
LLM-based interactive workflow planner for AKD.

This module provides an intelligent planner that can converse with users to understand
their research requirements and generate validated workflow definitions in the AKD format.
"""

from enum import Enum
from typing import Any, Optional

from loguru import logger
from pydantic import Field

from akd._base import InputSchema, OutputSchema
from akd.agents._base import LiteLLMInstructorBaseAgent, BaseAgentConfig
from akd.configs.planner_prompts import (
    WORKFLOW_PLANNER_SYSTEM_PROMPT_TEMPLATE,
    WORKFLOW_INPUT_EXTRACTION_PROMPT_TEMPLATE,
)

from .registry import AgentRegistry, get_agent_registry
from .format_builder import WorkflowFormat
from .workflow_builder import WorkflowBuilder
from .field_mapping_registry import FieldMappingRegistry
from .field_mapping_generator import FieldMappingGenerator
from .structures import AgentSuggestion, PlannerConfig, WorkflowPlan


class ConversationPhase(str, Enum):
    """Phases of the planning conversation."""

    INITIAL_REQUIREMENTS = "initial_requirements"
    GOAL_CLARIFICATION = "goal_clarification"
    AGENT_SELECTION = "agent_selection"
    IO_SPECIFICATION = "io_specification"
    WORKFLOW_CONSTRUCTION = "workflow_construction"
    VALIDATION = "validation"
    FINALIZATION = "finalization"


class PlannerQuestionType(str, Enum):
    """Types of questions the planner can ask."""

    OPEN_ENDED = "open_ended"
    MULTIPLE_CHOICE = "multiple_choice"
    CONFIRMATION = "confirmation"
    SPECIFICATION = "specification"


class PlannerQuestion(OutputSchema):
    """Question generated by the planner."""

    question: str = Field(..., description="The question to ask the user")
    question_type: PlannerQuestionType = Field(..., description="Type of question")
    options: Optional[list[str]] = Field(
        default=None, description="Options for multiple choice questions"
    )
    context: str = Field(
        ..., description="Context explaining why this question is important"
    )
    suggested_answer: Optional[str] = Field(
        default=None, description="Suggested answer if applicable"
    )


# AgentSuggestion and WorkflowPlan are now imported from structures.py


class PlannerResponse(OutputSchema):
    """Response from the planner agent."""

    message: str = Field(..., description="Response message to the user")
    phase: ConversationPhase = Field(..., description="Current conversation phase")
    question: Optional[PlannerQuestion] = Field(
        default=None, description="Follow-up question if needed"
    )
    workflow_plan: Optional[WorkflowPlan] = Field(
        default=None, description="Generated workflow plan"
    )
    ready_to_generate: bool = Field(
        default=False, description="Whether ready to generate final workflow"
    )


class PlannerInput(InputSchema):
    """Input to the planner agent."""

    user_message: str = Field(..., description="User's message or response")
    conversation_history: list[dict[str, str]] = Field(
        default_factory=list, description="Previous conversation"
    )
    current_phase: ConversationPhase = Field(
        default=ConversationPhase.INITIAL_REQUIREMENTS
    )
    available_agents: list[dict[str, Any]] = Field(
        default_factory=list, description="Available agents from registry"
    )


class LLMWorkflowPlanner(LiteLLMInstructorBaseAgent[PlannerInput, PlannerResponse]):
    """LLM-based workflow planner with conversational interface using LiteLLM."""

    input_schema = PlannerInput
    output_schema = PlannerResponse

    def __init__(
        self,
        config: Optional[BaseAgentConfig] = None,
        planner_config: Optional[PlannerConfig] = None,
        registry: Optional[AgentRegistry] = None,
        mapping_registry: Optional[FieldMappingRegistry] = None,
        mapping_generator: Optional[FieldMappingGenerator] = None,
        debug: bool = False,
    ):
        """
        Initialize the planner.

        Args:
            config: Agent-level configuration (model, API keys, etc.)
            planner_config: Planner-specific configuration (thresholds, temperatures, etc.)
            registry: Agent registry
            mapping_registry: Field mapping registry
            mapping_generator: Field mapping generator
            debug: Enable debug mode
        """
        self.registry = registry or get_agent_registry()
        self.mapping_registry = mapping_registry or FieldMappingRegistry()
        self.mapping_generator = mapping_generator or FieldMappingGenerator()
        self.builder = WorkflowBuilder(self.registry, self.mapping_registry, debug=debug)
        self.conversation_state: dict[str, Any] = {}
        self.planner_config = planner_config or PlannerConfig()
        self.debug = debug

        # Set up system prompt for workflow planning (uses self.registry)
        agent_config = config or BaseAgentConfig()
        agent_config.system_prompt = self._get_planner_system_prompt()
        # Use planner config temperature
        if not agent_config.temperature:
            agent_config.temperature = self.planner_config.temperature

        super().__init__(config=agent_config, debug=debug)

    def _get_planner_system_prompt(self) -> str:
        """Get the system prompt for the planner using optimized template from config."""
        # Build available agents section dynamically from registry
        agents_info = []
        for agent in self.registry.get_enabled_agents():
            agent_desc = f"- {agent.agent_id}: {agent.description}"

            # Add input/output info
            inputs = [f.name for f in agent.input_schema.fields if f.required]
            outputs = [f.name for f in agent.output_schema.fields]

            if inputs:
                agent_desc += f"\n  Required inputs: {', '.join(inputs)}"
            if outputs:
                agent_desc += f"\n  Outputs: {', '.join(outputs)}"

            agents_info.append(agent_desc)

        available_agents_text = "\n".join(agents_info) if agents_info else "No agents available"

        # Use optimized template from config
        return WORKFLOW_PLANNER_SYSTEM_PROMPT_TEMPLATE.format(
            available_agents=available_agents_text
        )

    def reset_conversation(self) -> None:
        """Reset the conversation state."""
        self.conversation_state = {}
        self.reset_memory()

    async def plan_workflow(self, initial_request: str) -> "InteractivePlannerSession":
        """Start an interactive planning session."""
        return InteractivePlannerSession(self, initial_request)

    async def _arun(self, params: PlannerInput, **kwargs) -> PlannerResponse:
        """Process user input and generate planner response."""
        try:
            # Get available agents information with detailed schemas
            available_agents = []
            for agent in self.registry.get_enabled_agents():
                agent_info = {
                    "id": agent.agent_id,
                    "name": agent.name,
                    "description": agent.description,
                    "input_schema": [
                        {
                            "name": f.name,
                            "type": f.type,
                            "description": f.description,
                            "required": f.required,
                        }
                        for f in agent.input_schema.fields
                    ],
                    "output_schema": [
                        {
                            "name": f.name,
                            "type": f.type,
                            "description": f.description,
                        }
                        for f in agent.output_schema.fields
                    ],
                    "use_cases": agent.use_cases,
                    "tags": agent.tags,
                }
                available_agents.append(agent_info)

            # Update input with available agents
            params.available_agents = available_agents

            # Build messages for LLM
            messages = [self._default_system_message()]

            # Add conversation history
            for msg in params.conversation_history:
                messages.append(msg)

            # Add current user message
            messages.append(
                {
                    "role": "user",
                    "content": f"Current phase: {params.current_phase}\nUser message: {params.user_message}",
                }
            )

            # Get response from LLM
            response = await self.get_response_async(messages)

            if self.debug:
                logger.debug(f"Planner response: {response}")

            return response

        except Exception as e:
            logger.error(f"Error in planner execution: {e}")
            return PlannerResponse(
                message=f"I encountered an error while processing your request: {e}",
                phase=params.current_phase,
                ready_to_generate=False,
            )


class InteractivePlannerSession:
    """Interactive session for workflow planning."""

    def __init__(self, planner: LLMWorkflowPlanner, initial_request: str):
        """Initialize planning session."""
        self.planner = planner
        self.initial_request = initial_request
        self.conversation_history: list[dict[str, str]] = []
        self.current_phase = ConversationPhase.INITIAL_REQUIREMENTS
        self.workflow_plan: Optional[WorkflowPlan] = None
        self.final_workflow: Optional[WorkflowFormat] = None

    async def start(self) -> PlannerResponse:
        """Start the planning conversation."""
        response = await self.planner._arun(
            PlannerInput(
                user_message=self.initial_request,
                conversation_history=self.conversation_history,
                current_phase=self.current_phase,
            )
        )

        self._update_session_state(self.initial_request, response)
        return response

    async def respond(self, user_message: str) -> PlannerResponse:
        """Process user response and continue conversation."""
        response = await self.planner._arun(
            PlannerInput(
                user_message=user_message,
                conversation_history=self.conversation_history,
                current_phase=self.current_phase,
            )
        )

        self._update_session_state(user_message, response)
        return response

    def _update_session_state(
        self, user_message: str, response: PlannerResponse
    ) -> None:
        """Update session state with new messages."""
        self.conversation_history.append({"role": "user", "content": user_message})
        self.conversation_history.append(
            {"role": "assistant", "content": response.message}
        )

        self.current_phase = response.phase

        if response.workflow_plan:
            self.workflow_plan = response.workflow_plan

    async def generate_workflow(self) -> WorkflowFormat:
        """Generate the final workflow from the conversation."""
        if not self.workflow_plan:
            raise ValueError(
                "No workflow plan available. Continue the conversation first."
            )

        # Simple validation: check agents exist
        missing_agents = self.planner.builder.check_missing_agents(self.workflow_plan)
        if missing_agents:
            raise ValueError(f"Agents not found in registry: {missing_agents}")

        # Fill inputs for each agent
        filled_inputs = await self._fill_all_agent_inputs(self.workflow_plan)

        # Check for unmapped fields that need LLM generation
        unmapped = self.planner.builder.identify_unmapped_fields(
            self.workflow_plan,
            filled_inputs
        )

        # Generate and approve field mappings if needed
        if unmapped:
            logger.info(f"Found {len(unmapped)} unmapped field sets requiring LLM mapping")
            await self._handle_unmapped_fields(unmapped)

        # Build workflow with io_map for runtime data flow
        workflow = self.planner.builder.build(self.workflow_plan, filled_inputs)

        if self.planner.debug:
            logger.debug(f"Generated workflow with {len(workflow.nodes)} nodes")

        self.final_workflow = workflow
        return workflow

    async def _handle_unmapped_fields(
        self,
        unmapped: list[dict[str, Any]],
        confidence_threshold: Optional[float] = None
    ) -> None:
        """
        Generate LLM mappings for unmapped fields and handle user approval.

        Args:
            unmapped: List of unmapped field info from identify_unmapped_fields()
            confidence_threshold: Threshold for auto-approval (uses planner config if None)
        """
        if confidence_threshold is None:
            confidence_threshold = self.planner.planner_config.field_mapping_confidence_threshold
        for item in unmapped:
            source_agent_id = item["source_agent_id"]
            target_agent_id = item["target_agent_id"]
            unmapped_fields = item["unmapped_fields"]

            source_agent = self.planner.registry.get_agent(source_agent_id)
            target_agent = self.planner.registry.get_agent(target_agent_id)

            if not source_agent or not target_agent:
                logger.error(
                    f"Cannot generate mapping: agent not found "
                    f"({source_agent_id} or {target_agent_id})"
                )
                continue

            logger.info(
                f"Generating LLM mapping for {source_agent_id} -> {target_agent_id}"
            )

            # Generate mapping using LLM
            try:
                result = await self.planner.mapping_generator.generate_mapping(
                    source_agent,
                    target_agent,
                    unmapped_fields
                )

                # Check if approval needed
                needs_approval = self.planner.mapping_generator.should_request_approval(
                    result,
                    confidence_threshold
                )

                if needs_approval:
                    # Format approval message
                    approval_msg = self.planner.mapping_generator.format_approval_message(
                        source_agent,
                        target_agent,
                        result
                    )

                    # Log approval request (in interactive mode, this would prompt user)
                    logger.info(f"\n{approval_msg}")
                    logger.warning(
                        "Low confidence mapping detected. Approval required. "
                        "Auto-approving for now (interactive mode not implemented)."
                    )

                    # TODO: In full interactive mode, wait for user approval here
                    # For now, auto-approve with warning
                    user_approved = True
                else:
                    user_approved = True
                    logger.info(
                        f"Auto-approved mapping with confidence {result.overall_confidence:.2f}"
                    )

                # Save mapping to registry
                mapping_dict = self.planner.mapping_generator.convert_to_mapping_dict(result)
                reasoning_dict = self.planner.mapping_generator.extract_reasoning(result)

                self.planner.mapping_registry.save_llm_mapping(
                    source_agent_id,
                    target_agent_id,
                    mapping_dict,
                    result.overall_confidence,
                    user_approved,
                    reasoning_dict
                )

                logger.info(
                    f"Saved LLM mapping: {source_agent_id} -> {target_agent_id} "
                    f"(approved={user_approved})"
                )

            except Exception as e:
                logger.error(
                    f"Failed to generate LLM mapping for "
                    f"{source_agent_id} -> {target_agent_id}: {e}"
                )

    async def _fill_all_agent_inputs(self, plan: WorkflowPlan) -> dict[str, dict[str, Any]]:
        """
        Fill inputs for all agents in the plan using full conversation context.

        Uses conversation history, workflow plan, and agent selection reasoning
        to extract context-aware input values.
        """
        filled_inputs = {}

        for agent_suggestion in plan.suggested_agents:
            agent_id = agent_suggestion.agent_id
            agent = self.planner.registry.get_agent(agent_id)

            if not agent:
                logger.warning(f"Agent {agent_id} not in registry, skipping")
                continue

            try:
                inputs = await self._fill_inputs_with_llm(
                    agent,
                    agent_id,
                    agent_suggestion,  # Pass agent suggestion for context
                    plan  # Pass full workflow plan for research goal
                )
                filled_inputs[agent_id] = inputs
            except Exception as e:
                logger.warning(f"Failed to fill inputs for {agent_id}: {e}")
                # Fallback to rule-based
                inputs = self._fallback_input_extraction(agent, agent_id)
                filled_inputs[agent_id] = inputs

        return filled_inputs

    async def _fill_inputs_with_llm(
        self,
        agent: Any,
        agent_id: str,
        agent_suggestion: AgentSuggestion,
        workflow_plan: Optional[WorkflowPlan] = None
    ) -> dict[str, Any]:
        """
        Use Instructor LLM to extract structured input values from full conversation context.

        Uses:
        - Initial user request
        - Full conversation history
        - Research goal and workflow description
        - Agent selection reasoning
        - Agent field schemas
        """
        from pydantic import create_model, Field as PydanticField

        # Build a dynamic Pydantic model from the agent's input schema
        field_definitions = {}
        field_descriptions = {}

        for field in agent.input_schema.fields:
            # Determine Python type from string type
            python_type = Any
            if "string" in field.type.lower() or "str" in field.type.lower():
                python_type = str
            elif "int" in field.type.lower():
                python_type = int
            elif "float" in field.type.lower() or "number" in field.type.lower():
                python_type = float
            elif "bool" in field.type.lower():
                python_type = bool
            elif "list" in field.type.lower() or "array" in field.type.lower():
                python_type = list[str]  # Default to list of strings

            # Make ALL fields Optional to allow LLM to omit auto-mapped fields
            # We filter out None values later - this allows LLM to skip fields that
            # will be populated by previous agent outputs via io_map
            python_type = Optional[python_type]

            # Store description
            description = field.description or f"{field.name} for {agent_id}"
            field_descriptions[field.name] = description

            # All fields have default=None so LLM can omit auto-mapped fields
            field_definitions[field.name] = (
                python_type,
                PydanticField(default=None, description=description)
            )

        # Create dynamic model
        InputModel = create_model(
            f"{agent_id.title()}Input",
            **field_definitions
        )

        # Use Instructor to extract structured data
        try:
            client = self.planner.client

            # Build conversation context (last 10 messages for context window management)
            conversation_history_text = ""
            if self.conversation_history:
                recent_messages = self.conversation_history[-10:]
                conversation_history_text = "\n".join([
                    f"{msg['role'].title()}: {msg['content']}"
                    for msg in recent_messages
                ])

            # Build research context from workflow plan
            research_context_text = ""
            if workflow_plan:
                research_context_text = f"Research Goal: {workflow_plan.research_goal}\nWorkflow Description: {workflow_plan.workflow_description}"

            # Build workflow position context
            agent_names = [a.agent_id for a in workflow_plan.suggested_agents] if workflow_plan else []
            current_idx = agent_names.index(agent_id) if agent_id in agent_names else -1
            workflow_position = f"Position {current_idx + 1} of {len(agent_names)}" if current_idx >= 0 else "Unknown"
            downstream_agents = ", ".join(agent_names[current_idx + 1:]) if current_idx >= 0 and current_idx < len(agent_names) - 1 else "Final agent"

            # Check for available field mappings from previous agent
            auto_mapped_fields = []
            if current_idx > 0 and workflow_plan:
                prev_agent_id = agent_names[current_idx - 1]
                # Get mapping from registry (via planner object)
                mapping = self.planner.mapping_registry.get_mapping(prev_agent_id, agent_id)
                if mapping:
                    auto_mapped_fields = list(mapping.keys())
                else:
                    # Check for exact name matches with previous agent outputs
                    prev_agent = self.planner.registry.get_agent(prev_agent_id)
                    if prev_agent:
                        prev_output_names = {f.name for f in prev_agent.output_schema.fields}
                        current_input_names = {f.name for f in agent.input_schema.fields}
                        auto_mapped_fields = list(prev_output_names & current_input_names)

            auto_mapped_text = ", ".join(auto_mapped_fields) if auto_mapped_fields else "None"

            # Combine all context sections
            context_sections = f"""Conversation History:
{conversation_history_text if conversation_history_text else 'No conversation history available'}

Research Context:
{research_context_text if research_context_text else 'No workflow plan available'}

Auto-Mapped Fields (DO NOT EXTRACT):
The following fields will be automatically populated from previous agent outputs at runtime: {auto_mapped_text}
These fields should be OMITTED from your output entirely."""

            # Separate required and optional inputs
            required_inputs_text = "\n".join([
                f"- {name}: {desc}"
                for name, desc in field_descriptions.items()
                if any(f.name == name and f.required for f in agent.input_schema.fields)
            ])
            optional_inputs_text = "\n".join([
                f"- {name}: {desc}"
                for name, desc in field_descriptions.items()
                if any(f.name == name and not f.required for f in agent.input_schema.fields)
            ])

            # Use optimized template from config
            prompt = WORKFLOW_INPUT_EXTRACTION_PROMPT_TEMPLATE.format(
                context_sections=context_sections,
                agent_id=agent_id,
                agent_description=agent.description if hasattr(agent, 'description') else 'N/A',
                selection_reason=agent_suggestion.reason,
                confidence=agent_suggestion.confidence,
                workflow_position=workflow_position,
                downstream_agents=downstream_agents,
                required_inputs=required_inputs_text if required_inputs_text else "None",
                optional_inputs=optional_inputs_text if optional_inputs_text else "None",
                dependencies=", ".join(agent_suggestion.depends_on) if agent_suggestion.depends_on else "None",
                expected_outputs=", ".join(agent_suggestion.expected_outputs) if agent_suggestion.expected_outputs else "Not specified"
            )

            response = await client.chat.completions.create(
                model=self.planner.config.model_name,
                response_model=InputModel,
                messages=[
                    {"role": "system", "content": "You are an expert at extracting structured input parameters for research agents. Extract values from the provided context and return them in the exact schema format required."},
                    {"role": "user", "content": prompt}
                ],
                temperature=self.planner.planner_config.input_extraction_temperature,
            )

            # Convert to dict and filter out None values (auto-mapped fields)
            result = response.model_dump()
            # Remove None values - these are fields LLM correctly omitted (will be auto-mapped)
            return {k: v for k, v in result.items() if v is not None}

        except Exception as e:
            logger.warning(f"LLM-based input filling failed for {agent_id}: {e}")
            # Fall back to simpler extraction
            return self._fallback_input_extraction(agent, agent_id)

    def _fallback_input_extraction(self, agent: Any, agent_id: str) -> dict[str, Any]:
        """
        Fallback extraction using only schema defaults and generic field name patterns.

        No hardcoded domain knowledge - uses only:
        1. Schema-defined defaults
        2. Generic pattern: fields named 'query'/'queries' get user request
        3. Type-based defaults
        """
        user_query = self.initial_request
        result = {}

        for field in agent.input_schema.fields:
            value = None

            # Use schema default if available
            if field.default is not None:
                value = field.default
            # Generic pattern: any field named 'query' or 'queries' gets user request
            elif field.name in ["query", "queries"]:
                value = [user_query] if field.type == "array" else user_query
            # Type-based defaults for required fields
            else:
                value = self._get_type_default(field.type)

            result[field.name] = value

        return result

    def _get_type_default(self, field_type: str) -> Any:
        """Get default value based on field type."""
        type_defaults = {
            "string": "",
            "integer": 0,
            "number": 0.0,
            "boolean": False,
            "array": [],
            "object": {}
        }
        return type_defaults.get(field_type, None)


    def get_conversation_summary(self) -> str:
        """Get a summary of the conversation."""
        summary = "Planning Session Summary:\n"
        summary += f"Initial Request: {self.initial_request}\n"
        summary += f"Current Phase: {self.current_phase}\n"

        if self.workflow_plan:
            summary += f"Research Goal: {self.workflow_plan.research_goal}\n"
            summary += f"Suggested Agents: {[a.agent_name for a in self.workflow_plan.suggested_agents]}\n"

        return summary


# Convenience functions
async def create_planner(
    config: Optional[BaseAgentConfig] = None, registry: Optional[AgentRegistry] = None
) -> LLMWorkflowPlanner:
    """Create a new workflow planner instance."""
    return LLMWorkflowPlanner(config=config, registry=registry)


async def quick_plan(
    research_goal: str, config: Optional[BaseAgentConfig] = None
) -> InteractivePlannerSession:
    """Create a quick planning session for a research goal."""
    planner = await create_planner(config=config)
    return await planner.plan_workflow(research_goal)
