from functools import partial
from typing import Optional

from langchain_community.vectorstores import InMemoryVectorStore
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, START, StateGraph
from langgraph.types import RetryPolicy
from loguru import logger
from pydantic import AliasChoices, Field

from akd._base import InputSchema, OutputSchema
from akd.agents._base import BaseAgent, BaseAgentConfig
from akd.agents.search.aspect_search import AspectSearchConfig

from .nodes import (
    conduct_interviews,
    index_references,
    initialize_research,
    refine_outline,
    write_article,
    write_sections,
)
from .structures import Perspectives, ResearchState


class StormInputSchema(InputSchema):
    """Input schema for storm agent"""

    config: dict | None = Field(
        default={"configurable": {"thread_id": "default-thread"}},
        description="The configuration dict to track the state of the storm agent.",
    )
    topic: str = Field(
        ...,
        validation_alias=AliasChoices("topic", "query"),
        description="The topic to create the article for.",
    )


class StormOutputSchema(OutputSchema):
    """Output schema for storm agent"""

    article: str = Field(
        ...,
        description="The article generated by storm",
    )
    perspectives: Perspectives = Field(
        ...,
        description="List of editors working on the article",
    )
    references: dict = Field(
        ...,
        description="References collected by aspect search",
    )


class StormAgentConfig(BaseAgentConfig):
    """Configuration for Storm Agent"""

    long_context_llm: str = Field(
        default="gpt-4o-mini",
        description="Model used for longer context based operations",
    )
    aspect_search_config: Optional[object] = Field(
        default_factory=AspectSearchConfig,
        description="Aspect search configuration",
    )
    embedding_model: str = Field(
        default="ibm-granite/granite-embedding-small-english-r2",
        description="Embedding model to index referenced documents.",
    )
    in_memory_vector_store: Optional[object] = Field(
        default=InMemoryVectorStore,
        description="Default vector store used for in-memory operations",
    )
    writer_context_k: int = Field(
        default=3,
        description="Top k context to retrieve for the writer",
    )
    max_attempts: int = Field(
        default=3,
        description="Maximum number of attempts to make before giving up, including the first",
    )


class StormAgent(BaseAgent):
    input_schema = StormInputSchema
    output_schema = StormOutputSchema
    config_schema = StormAgentConfig

    def _post_init(
        self,
    ) -> None:
        super()._post_init()

        self.fast_llm = ChatOpenAI(
            model=self.config.model_name,
            temperature=self.config.temperature,
            api_key=self.config.api_key,
        )

        self.long_context_llm = ChatOpenAI(
            model=self.config.long_context_llm,
            temperature=self.config.temperature,
            api_key=self.config.api_key,
        )

        self.vectorstore = self.config.in_memory_vector_store(
            embedding=HuggingFaceEmbeddings(
                model_name=self.config.embedding_model,
                model_kwargs={"device": "cpu"},
            ),
        )
        self.retriever = self.vectorstore.as_retriever(k=self.config.writer_context_k)

        storm_builder = StateGraph(ResearchState)

        nodes = [
            (
                "init_research",
                partial(
                    initialize_research,
                    fast_llm=self.fast_llm,
                ),
            ),
            (
                "conduct_interviews",
                partial(
                    conduct_interviews,
                    aspect_search_config=self.config.aspect_search_config,
                ),
            ),
            (
                "refine_outline",
                partial(
                    refine_outline,
                    long_context_llm=self.long_context_llm,
                ),
            ),
            (
                "index_references",
                partial(
                    index_references,
                    vector_store=self.vectorstore,
                ),
            ),
            (
                "write_sections",
                partial(
                    write_sections,
                    long_context_llm=self.long_context_llm,
                    retriever=self.retriever,
                ),
            ),
            (
                "write_article",
                partial(
                    write_article,
                    long_context_llm=self.long_context_llm,
                ),
            ),
        ]
        nodes = [node for node in nodes if node is not None]

        for i in range(len(nodes)):
            name, node = nodes[i]
            storm_builder.add_node(
                name,
                node,
                retry=RetryPolicy(max_attempts=self.config.max_attempts),
            )
            if i > 0:
                storm_builder.add_edge(nodes[i - 1][0], name)

        storm_builder.add_edge(START, nodes[0][0])
        storm_builder.add_edge(nodes[-1][0], END)
        self.storm = storm_builder.compile(checkpointer=MemorySaver())

    async def get_response_async(
        self,
        params: StormInputSchema,
        **kwargs,
    ) -> StormOutputSchema:
        """
        Obtains a response from the language model asynchronously.

        Args:
            response_model (Optional[OutputSchema]):
                The schema for the response data. If not set,
                self.output_schema is used.

        Returns:
            OutputSchema: The response from the language model.
        """
        config = params.config
        topic = params.topic
        if self.config.debug:
            async for chunk in self.storm.astream(
                {"topic": topic},
                config=config,
                stream_mode="values",
                debug=self.config.debug,
            ):
                logger.debug(chunk)
            article_state = self.storm.get_state(config=config).values
        else:
            article_state = await self.storm.ainvoke(
                {"topic": topic},
                config=config,
            )
        article = article_state["article"]
        perspectives = article_state["perspectives"]
        references = article_state["references"]
        return StormOutputSchema(
            article=article,
            perspectives=perspectives,
            references=references,
        )

    async def _arun(self, params: StormInputSchema, **kwargs) -> StormOutputSchema:
        return await self.get_response_async(params, **kwargs)
