
from langgraph.graph import END, StateGraph, START
from langgraph.checkpoint.memory import MemorySaver
from langgraph.pregel import RetryPolicy
from pydantic import BaseModel, Field

from ..tools.storm.state import ResearchState
from ..tools.storm.nodes import *
from ..tools.storm.config import initialise_storm_config
from ..configs.storm_config import StormSettings, STORM_SETTINGS


class StormInputSchema(BaseModel):
    """Input schema for storm agent"""
    config: dict = Field(
        ...,
        description="The configuration dict to track the state of the storm agent.",
    )
    topic: str = Field(
        ...,
        description="The topic to create the article for.",
    )


class StormOutputSchema(BaseModel):
    """Output schema for storm agent"""
    article: str = Field(
        ...,
        description="The article generated by storm.",
    )


class StormAgent():

    input_schema = StormInputSchema
    output_schema = StormOutputSchema

    def __init__(
        self,
        config: Optional[StormSettings] = None,
    ) -> None:
        
        # Set this configuration 
        config = config or STORM_SETTINGS
        initialise_storm_config(config)

        builder_of_storm = StateGraph(ResearchState)

        nodes = [
            ("init_research", initialize_research),
            ("conduct_interviews", conduct_interviews),
            ("refine_outline", refine_outline),
            ("index_references", index_references),
            ("write_sections", write_sections),
            ("write_article", write_article),
        ]

        for i in range(len(nodes)):
            name, node = nodes[i]
            builder_of_storm.add_node(name, node, retry=RetryPolicy(max_attempts=3))
            if i > 0:
                builder_of_storm.add_edge(nodes[i - 1][0], name)


        builder_of_storm.add_edge(START, nodes[0][0])
        builder_of_storm.add_edge(nodes[-1][0], END)
        self.storm = builder_of_storm.compile(checkpointer=MemorySaver())

    
    async def arun(self, params: StormInputSchema) -> StormOutputSchema:

        config = params.config
        topic = params.topic

        article_state = await self.storm.ainvoke({"topic": topic}, config,)
        article = article_state['article']
        return article