version: '3.7'

services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:ro
      - searxng-data:/var/log/searxng
    environment:
      - BIND_ADDRESS=0.0.0.0:8080
      - BASE_URL=http://localhost:8080/
      - MORTY_URL=
      - MORTY_KEY=
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  searxng-data:
    driver: local