use_default_settings: true

general:
  debug: true
  instance_name: "SearxNG Standalone"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - json
    - html
    - rss

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "standalone_secret_key_12345"
  base_url: "http://localhost:8080/"
  image_proxy: false
  http_protocol_version: "1.1"
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

ui:
  static_use_hash: false
  default_locale: ""
  query_in_title: false
  infinite_scroll: false
  center_alignment: false
  cache_url: "https://web.archive.org/web/"
  search_on_category_select: true
  hotkeys: default

# Enable only science engines; disable general/news/video
engines:
  - name: google
    disabled: true

  - name: bing
    disabled: true

  - name: duckduckgo
    disabled: true

  - name: wikipedia
    disabled: true

  - name: google scholar
    disabled: false

  - name: arxiv
    disabled: false

  - name: pubmed
    disabled: false

  - name: semantic scholar
    disabled: false

  - name: crossref
    disabled: false
